Update to Kotlin 1.0.0. + Json Remote Command
Tealium/tealium-android-firebase-remote-command pull request #5
Opened 2020-10-22 03:46 UTC by tamayok

2020-10-22 10:31 UTC, jameskeith requested changes

2020-10-22 10:31 UTC, jameskeith commented on gradle.properties
> +android.enableJetifier=true
removing the dummy credentials will cause build issues for anyone who does not have the AWS_ACCESS_KEY/AWS_SECRET_KEY set in their global `~/.gradle/gradle.properties` file
If we're removing these, can we comment out the `repositories { }` block in `firebase/build.gradle` too?

2020-10-22 16:10 UTC, tamayok commented on gradle.properties
> +android.enableJetifier=true
Good call. I'll comment out that block in the gradle file. I believe we do this in main Kotlin lib as well.

2020-10-22 16:55 UTC, tamayok commented on firebase/src/main/java/com/tealium/remotecommands/firebase/FirebaseConstants.java
> +        //        public static final String EVENT_PARAMS = "firebase_event_params";
Addressed.

2020-11-10 15:15 UTC, jameskeith approved these changes
lgtm

2020-11-10 16:09 UTC, merged